config:
  zsh:
    zshrc: ~/.zshrc
    zshenv: ~/.zshenv
  aws:
    config: ~/.aws/config
  fish:
    config.fish: ~/.config/fish/config.fish
  git:
    gitconfig: ~/.gitconfig
    ignore: ~/.config/git/ignore
  ruby:
    gemrc: ~/.gemrc
  rails:
    railsrc: ~/.railsrc
  vim:
    vimrc: ~/.vimrc
