config:
  zsh:
    zshrc: ~/.zshrc
  direnv:
    direnvrc: ~/.direnvrc
  vim:
    vimrc: ~/.vimrc
  git:
    gitconfig: ~/.gitconfig
    ignore: ~/.config/git/ignore
  ruby:
    gemrc: ~/.gemrc
  rails:
    railsrc: ~/.railsrc
  fixpack:
    fixpackrc: ~/.fixpackrc
  peco:
    config.json: ~/.config/peco/config.json
  karabiner:
    karabiner.json: ~/.config/karabiner/karabiner.json