config:
  zsh:
    zshrc: ~/.zshrc
  aws:
    config: ~/.aws/config
  git:
    gitconfig: ~/.gitconfig
    ignore: ~/.config/git/ignore
  ruby:
    gemrc: ~/.gemrc
  rails:
    railsrc: ~/.railsrc
  vim:
    vimrc: ~/.vimrc
