bootstrap:
  zsh: brew install zsh getantibody/antibody/antibody mas
  fish: brew install fish
  ruby: brew install ruby
  rails: gem install rails
  vim: brew install vim
caveat:
  git:
    local: ~/.gitconfig.local
  aws:
    secrets: ~/.aws/credentials
  zsh:
    local: ~/.zshrc.local
  node:
    message: Put $NPM_TOKEN into .zshrc.local
config:
  zsh:
    zshrc: ~/.zshrc
  aws:
    config: ~/.aws/config
  fish:
    config.fish: ~/.config/fish/config.fish
  git:
    gitconfig: ~/.gitconfig
    ignore: ~/.config/git/ignore
  node:
    npmrc: ~/.npmrc
  ruby:
    gemrc: ~/.gemrc
  rails:
    railsrc: ~/.railsrc
  vim:
    vimrc: ~/.vimrc
