config:
  direnv:
    direnvrc: ~/.direnvrc
  fixpack:
    fixpackrc: ~/.fixpackrc
  git:
    gitconfig: ~/.gitconfig
    ignore: ~/.config/git/ignore
  hammerspoon:
    hammerspoon: ~/.hammerspoon
  htop:
    htoprc: ~/.config/htop/htoprc
  lepton:
    leptonrc: ~/.leptonrc
  peco:
    config.json: ~/.config/peco/config.json
  poetry:
    config.toml: ~/Library/Application Support/pypoetry/config.toml
  rails:
    railsrc: ~/.railsrc
  ruby:
    gemrc: ~/.gemrc
    bundler: ~/.bundle/config
  screen:
    screenrc: ~/.screenrc
  vim:
    vimrc: ~/.vimrc
  vscode:
    settings.json: ~/Library/Application Support/Code/User/settings.json
    keybindings.json: ~/Library/Application Support/Code/User/keybindings.json
    snippets: ~/Library/Application Support/Code/User/snippets
  zsh:
    zshrc: ~/.zshrc
