config:
  zsh:
    zshrc: ~/.zshrc
  direnv:
    direnvrc: ~/.direnvrc
  vim:
    vimrc: ~/.vimrc
  git:
    gitconfig: ~/.gitconfig
    ignore: ~/.config/git/ignore
  ruby:
    gemrc: ~/.gemrc
    bundler: ~/.bundle/config
  rails:
    railsrc: ~/.railsrc
  fixpack:
    fixpackrc: ~/.fixpackrc
  peco:
    config.json: ~/.config/peco/config.json
  karabiner:
    karabiner.json: ~/.config/karabiner/karabiner.json
  poetry:
    config.toml: ~/Library/Application Support/pypoetry/config.toml
  vscode:
    settings.json: ~/Library/Application Support/Code/User/settings.json
    keybindings.json: ~/Library/Application Support/Code/User/keybindings.json
    snippets/javascript.json: ~/Library/Application Support/Code/User/snippets/javascript.json
    snippets/typescript.json: ~/Library/Application Support/Code/User/snippets/typescript.json
    snippets/python.json: ~/Library/Application Support/Code/User/snippets/python.json
    snippets/rust.json: ~/Library/Application Support/Code/User/snippets/rust.json
  lepton:
    leptonrc: ~/.leptonrc
