config:
  direnv:
    direnvrc: ~/.config/direnv/direnvrc
  fixpack:
    fixpackrc: ~/.fixpackrc
  git:
    gitconfig: ~/.gitconfig
    ignore: ~/.config/git/ignore
  hammerspoon:
    hammerspoon: ~/.hammerspoon
  lepton:
    leptonrc: ~/.leptonrc
  neofetch:
    config.conf: ~/.config/neofetch/config.conf
    motd: ~/.motd
  peco:
    config.json: ~/.config/peco/config.json
  poetry:
    config.toml: ~/Library/Application Support/pypoetry/config.toml
  ruby:
    gemrc: ~/.gemrc
    bundler: ~/.bundle/config
  tmux:
    tmux.conf: ~/.tmux.conf
  vim:
    vimrc: ~/.vimrc
  vscode:
    settings.json: ~/Library/Application Support/Code/User/settings.json
    keybindings.json: ~/Library/Application Support/Code/User/keybindings.json
    snippets: ~/Library/Application Support/Code/User/snippets
  zsh:
    zshrc: ~/.zshrc
