" syntax highlighting
syntax on

" indentation
set autoindent " enable auto indent
set smartindent
set expandtab " tab key to spaces
set tabstop=4 " visual tab width
set shiftwidth=2 " auto indent width
set softtabstop=2 " spaces width

" highlight search term
set hlsearch
hi Search cterm=NONE ctermfg=Black ctermbg=Yellow

" cursor line
set cursorline
hi CursorLine term=bold cterm=bold

" set line number
"set number
"hi LineNr ctermfg=grey

" use tabs in Makefile
autocmd FileType make set noexpandtab shiftwidth=8 softtabstop=0
