export GH="https://github.com/uetchy"
export GHQ_ROOT="$HOME/Repos/src"

alias git="hub"
alias st="git status"
alias br="git branches"
alias remotes="git remotes"
alias pull="git pull --rebase"
alias push="git push"
alias pr="git pull-request"
alias gd="cd \$(git rev-parse --show-toplevel)"
alias gif="git diff"
alias recent="git recent"
alias stashall="git stash -u"
alias unstash="git stash pop"
alias set-upstream="git branch -u"
alias set-upstream-origin-master="git branch --set-upstream-to=origin/master master"
alias push-origin-master="git push -u origin master"
alias lg="lazygit"
alias fs="fork status"
alias u="git-cleanup && git pull"

function gi() {
  git ignore $1 > .gitignore
}

git-sync-origin() {
  git remote set-url origin $(git config github.user)/$(basename $PWD)
}

git-update-upstream() {
  if [[ `git remote | grep upstream` ]]; then
    echo "Getting update from upstream"
    git fetch --all --prune --tags
    git rebase origin/master master
    git rebase upstream/master master
    git push --set-upstream origin master
  elif [[ `git remote | grep uetchy` ]]; then
    echo "Getting update from origin"
    git fetch --all --prune --tags
    git rebase uetchy/master master
    git rebase origin/master master
    git push --set-upstream uetchy master
  fi
}

git-cleanup() {
  git fetch --all --prune --tags
  git branch --merged | grep -v '*' | xargs git branch --delete
  git-delete-squashed
  git branch -a
}

# https://github.com/not-an-aardvark/git-delete-squashed
git-delete-squashed() {
  git checkout -q master && git for-each-ref refs/heads/ "--format=%(refname:short)" | while read branch; do mergeBase=$(git merge-base master $branch) && [[ $(git cherry master $(git commit-tree $(git rev-parse $branch^{tree}) -p $mergeBase -m _)) == "-"* ]] && git branch -D $branch; done
}

gu() {
  local gtPrivateKeyPath=$(git config remote.origin.gtPrivateKeyPath)
  local privateKeyPath=${gtPrivateKeyPath:-$HOME/.ssh/id_rsa}
  local gitUser=$(git config user.name)
  local gitEmail=$(git config user.email)
  echo "Name: ${gitUser}"
  echo "Email: ${gitEmail}"
  echo "Key: ${privateKeyPath}"
  echo ""
  GIT_SSH_COMMAND="ssh -i ${privateKeyPath} -oIdentitiesOnly=yes" $@
}

git-bootstrap() {
  [ ! -d .git ] && git init
  touch README.md
  yo license
}

alias git-contributors="git shortlog -sn | awk -F '\t' 'BEGIN {print \"list of contributors, generated by \`git shortlog -sn\`.\n\"} {print \"- \" \$2}' | grep -Ev 'dependabot|travis|Greenkeeper'"

# GitHub
alias gh-repo="echo \${PWD#*\.*/}"
alias gh-token="cat $HOME/.config/hub | yq '.[][0].oauth_token' -r" 
alias get="ghq get"

gh-readme() {
  hub api search/repositories?q=$1 | jq -r '.items[0].html_url' | fetch-readme | mdcat
}

gh-open() {
  git api search/repositories?q=$1 | jq -r '.items[].html_url' | fzy | xargs open
}

gh-clone() {
  git api search/repositories?q=$1 | jq -r '.items[].full_name' | fzy | xargs ghq get
}

gh-purge() {
  curl -s -X PURGE $1 | jq .
}

# or `rel` would also works
gh-releases() {
  local result=$(git api repos/$(gh-repo)/releases)
  jq -r '.[] | "[\(.tag_name)]\n\(.html_url)\n"' <<<"${result}"
}

## Release
alias release-it="release-it --git.tagName='v\${version}'"

# ghq
function fast-ghq-list() {
  for i in $(fd . $GHQ_ROOT/*/* --type d -d 1); do
    if [[ $1 == '-p' ]]; then
      echo ${i}
    else
      echo ${i#$GHQ_ROOT/}
    fi
  done
}

function select-repo() {
  local selected_dir=$(fast-ghq-list | fzy --query "/")
  if [ -n "$selected_dir" ]; then
    if [[ -n $LBUFFER ]]; then
      BUFFER=$LBUFFER${GHQ_ROOT}/${selected_dir}/$RBUFFER
      CURSOR=$#BUFFER
      zle redisplay
    else
      BUFFER="cd \"${GHQ_ROOT}/${selected_dir}\" && clear"
      zle accept-line
    fi
  fi
}
zle -N select-repo
bindkey '^r' select-repo

function select-branch() {
  local branch=$(git branch -a --format '%(refname:short)' | fzy)
  BUFFER=$LBUFFER$branch$RBUFFER
  CURSOR=$#BUFFER
  zle redisplay
}
zle -N select-branch
bindkey '^b' select-branch

git-rename() {
  read OLD_EMAIL"?Your Old Email: "
  read CORRECT_NAME"?Your Correct Name: "
  read CORRECT_EMAIL"?Your Correct Email: "

  git filter-branch -f --env-filter "
  if [ "\$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
  then
      export GIT_COMMITTER_NAME="$CORRECT_NAME"
      export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
  fi
  if [ "\$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
  then
      export GIT_AUTHOR_NAME="$CORRECT_NAME"
      export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
  fi
  " --tag-name-filter cat -- --branches --tags
}
