# zmodload zsh/zprof && zprof

ZSHRC_DIR=${$(readlink ${(%):-%x}):h}
DOTFILES_DIR=${ZSHRC_DIR:h}

# Antibody
source <(/usr/local/opt/antibody/bin/antibody init)
antibody bundle mafredri/zsh-async # pure deps
antibody bundle sindresorhus/pure
antibody bundle zsh-users/zsh-syntax-highlighting
antibody bundle zsh-users/zsh-completions
antibody bundle t413/zsh-background-notify


# General Settings
setopt interactivecomments # allow to use '#' as starting comment line
# autoload -U colors; colors
# export LS_COLORS='di=01;34:ln=01;35:so=01;32:ex=01;31:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30'
export CLICOLOR=true


# Completion
autoload -U compinit; compinit -C
zstyle ':completion:*' use-cache on # completion caches
zstyle ':completion:*:functions' ignored-patterns '_*' # Ignore completion for non-existant commands
# zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# zstyle ':completion:*' completer _complete _match _approximate
# zstyle ':completion:*:approximate:*' max-errors 3 numeric # Fuzzy completion
zstyle ':completion:*:cd:*' ignore-parents parent pwd # cd will never select the parent directory (e.g.: cd ../<TAB>):
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' # insensitive completion

setopt auto_cd # move to directory without 'cd'
setopt correct
setopt notify # notify messages
setopt no_beep # no beep sound
export LANG="en_US.UTF-8"
export LC_ALL=$LANG
export EDITOR="vim"


# Key binding
bindkey -e


# History
HISTFILE="$HOME/.zsh_history"
HISTSIZE=5000
SAVEHIST=10000
setopt share_history
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_reduce_blanks


# zsh
alias reload="source ~/.zshrc"


# Sublime Text
alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias sl="subl ."


# iCloud
alias btmm='echo show Setup:/Network/BackToMyMac | scutil | awk -F" " "/$UID/{print \$NF}"'


# POSIX
alias la="ls -al"


# Git
alias git="hub"
alias gt="gittower ."
alias push="git push -u origin master"


# SSH
remote() {
  mosh $1 -- screen -qR
}

remote-ssh() {
  ssh $1 -t screen -q -D -RR
}

forward() {
  ssh -L $1:localhost:$1 -N $2
}


# Ruby
alias be="bundle exec"
alias bi="bundle install --without production:staging --path vendor/bundle --binstubs vendor/bundle/bin --jobs 4"

glar() {
  gem list --remote --all --pre "^${1}$"
}


# Python
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init - --quiet)"
alias pv="pyenv versions"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1

pip_update() {
  pip list --outdated | awk '{print $1}' | xargs pip install -U
}


# Node.js
export PATH="/usr/local/lib/node_modules:$PATH"
npm-hp() {
  npm info $1 homepage | xargs open
}


# Go
export GOPATH="$HOME/Repos"
export PATH=$PATH:$GOPATH/bin


# CUDA
# download at https://developer.nvidia.com/cuda-toolkit
export CUDA_HOME=/usr/local/cuda # Actual path is /Developer/NVIDIA/CUDA-7.5
export DYLD_LIBRARY_PATH="$CUDA_HOME/lib:$DYLD_LIBRARY_PATH"
export PATH="$CUDA_HOME/bin:$PATH"


# Android
export ANDROID_HOME=/usr/local/opt/android-sdk


# TeX
# export PATH="/Library/TeX/texbin:$PATH"


# Docker
alias d="docker"
alias da="docker ps -a"
alias di="docker images"
alias dlq="docker ps -lq"
alias dip="docker inspect \$(docker ps -lq) | grep IPAddress | cut -d '\"' -f 4"
alias drm="docker rm \$(docker ps -aq)"
alias drmf="docker rm -f \$(docker ps -aq)"
drmi() { for i in `docker images | grep \<none\> | awk '{print $3}'`; do docker rmi $i; done }

alias dc="docker-compose"
alias dm="docker-machine"
dmenv() {
  eval $(docker-machine env $1)
}


# travis
[ -f ~/.travis/travis.sh ] && source ~/.travis/travis.sh


# peco
function peco-src() {
    local selected_dir=$(ghq list | peco --query "$LBUFFER")
    if [ -n "$selected_dir" ]; then
        BUFFER="cd $(ghq root)/${selected_dir}"
        zle accept-line
    fi
    zle redisplay
}
zle -N peco-src
bindkey '^r' peco-src

function peco-select-history() {
    typeset tac
    if which tac > /dev/null; then
        tac=tac
    else
        tac='tail -r'
    fi
    BUFFER=$(fc -l -n 1 | eval $tac | awk '!a[$0]++' | peco --query "$LBUFFER")
    CURSOR=$#BUFFER
    zle redisplay
}
zle -N peco-select-history
bindkey '^h' peco-select-history


update() {
  pushd $DOTFILES_DIR && git pull && popd
  brew update && brew upgrade --all
  # brew cleanup
  gem update
  # gem cleanup
  apm update --no-confirm
  npm-check -gu
  pip_update
  gst update
}


gu() {
  gtPrivateKeyPath=$(git config remote.origin.gtPrivateKeyPath)
  privateKeyPath=${gtPrivateKeyPath:-~/.ssh/id_rsa}
  gitUser=$(git config user.name)
  gitEmail=$(git config user.email)
  echo "Name: ${gitUser}"
  echo "Mail: ${gitEmail}"
  echo "Private: ${privateKeyPath}"
  echo ""
  GIT_SSH_COMMAND="ssh -i ${privateKeyPath} -oIdentitiesOnly=yes" $@
}


# zprof
