# zmodload zsh/zprof && zprof

ZSHRC_DIR=${$(readlink ${(%):-%x}):h}
DOTFILES_DIR=${ZSHRC_DIR:h}

# Antibody
source <(antibody init)
antibody bundle mafredri/zsh-async # pure deps
antibody bundle sindresorhus/pure
antibody bundle zsh-users/zsh-syntax-highlighting
antibody bundle zsh-users/zsh-completions
antibody bundle t413/zsh-background-notify


# General Settings
setopt interactivecomments # allow to use '#' as starting comment line
# autoload -U colors; colors
# export LS_COLORS='di=01;34:ln=01;35:so=01;32:ex=01;31:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30'
export CLICOLOR=true


# Completion
autoload -U compinit; compinit -C
zstyle ':completion:*' use-cache on # completion caches
zstyle ':completion:*:functions' ignored-patterns '_*' # Ignore completion for non-existant commands
# zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# zstyle ':completion:*' completer _complete _match _approximate
# zstyle ':completion:*:approximate:*' max-errors 3 numeric # Fuzzy completion
zstyle ':completion:*:cd:*' ignore-parents parent pwd # cd will never select the parent directory (e.g.: cd ../<TAB>):
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' # insensitive completion

setopt auto_cd # move to directory without 'cd'
setopt correct
setopt notify # notify messages
setopt no_beep # no beep sound
export LANG="en_US.UTF-8"
export LC_ALL=$LANG
export EDITOR="vim"


# Key binding
bindkey -e


# History
HISTFILE="$HOME/.zsh_history"
HISTSIZE=5000
SAVEHIST=10000
setopt share_history
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_reduce_blanks


# patch
# if [ -x /usr/libexec/path_helper ]; then
# 	eval `/usr/libexec/path_helper -s`
# fi


# atom
alias ae="atom ."


# Visual Studio Code
alias vs="code ."


# zsh
alias reload="source ~/.zshrc"


# direnv
eval "$(direnv hook zsh)"


# Sublime Text
alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias sl="subl ."


# iCloud
alias btmm='echo show Setup:/Network/BackToMyMac | scutil | awk -F" " "/$UID/{print \$NF}"'


# POSIX
alias la="ls -al"


# Git
alias git="hub"
alias gt="gittower ."
alias push="git push -u origin master"

alias st="git status"
alias commit="git commit"


# SSH
remote() {
  ssh $1 -t 'screen -qR'
}

remosh() {
  mosh $1 -- screen -qR
}

forward() {
  ssh -L ${1}:localhost:${1} -N ${2}
}


# remote worker scripts
sk() {
  rsync -rv --exclude '.git*' . six:sync/$(basename $PWD)
}

run() {
  ssh -t six "cd sync/$(basename $PWD); $@"
}

skrun() {
  sk && echo '---' && run $@
}

ssh-mount() {
  mkdir ./$1
  sshfs $1: ./$1 -o volname=$1 -o cache_timeout=10
}

# Ruby
export PATH="./bin:$PATH"
alias be="bundle exec"
alias bi="bundle install --without production:staging --path vendor/bundle --binstubs vendor/bundle/bin --jobs 4"

glar() {
  gem list --remote --all --pre "^${1}$"
}


# Python
alias mkvenv="python3 -m venv venv"
alias activate="source venv/bin/activate"

pip-update() {
  pip list --format=legacy --outdated | awk '{print $1}' | xargs pip install -U
  pip3 list --format=legacy --outdated | awk '{print $1}' | xargs pip3 install -U
}


# Node.js
export PATH="/usr/local/lib/node_modules:$PATH"
alias npm-list="npm list -g --depth 0"
alias yui="yarn upgrade-interactive"


# Go
export GOPATH="$HOME/Repos"
export PATH=$PATH:$GOPATH/bin


# CUDA
# download at https://developer.nvidia.com/cuda-toolkit
export CUDA_HOME=/usr/local/cuda # Actual path is /Developer/NVIDIA/CUDA-8.0
export PATH="$CUDA_HOME/bin:$PATH"
export DYLD_LIBRARY_PATH="$CUDA_HOME/lib:$DYLD_LIBRARY_PATH"


# torch
if [ -x $HOME/torch/install/bin/torch-activate ]; then
  . $HOME/torch/install/bin/torch-activate
fi


# Google Cloud Platform
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'


# Android
#export ANDROID_HOME=/usr/local/opt/android-sdk


# TeX
# export PATH="/Library/TeX/texbin:$PATH"


# Docker
alias d="docker"
alias da="docker ps -a"
alias di="docker images"
alias dlq="docker ps -lq"
alias dip="docker inspect \$(docker ps -lq) | grep IPAddress | cut -d '\"' -f 4"
alias drm="docker ps -aqf status=exited | xargs docker rm -v"
alias drmi="docker images -qf dangling=true | xargs docker rmi"

alias dc="docker-compose"
alias dm="docker-machine"

dm-env() {
  eval $(docker-machine env $1)
}

dm-start() {
	docker-machine start default
	dm-env default
}


# travis
[ -f ~/.travis/travis.sh ] && source ~/.travis/travis.sh


# peco
function peco-src() {
  local selected_dir=$(ghq list -p | peco --query "$LBUFFER")
  if [ -n "$selected_dir" ]; then
    BUFFER="cd \"${selected_dir}\" && clear"
    zle accept-line
  fi
  zle redisplay
}
zle -N peco-src
bindkey '^r' peco-src

function peco-select-history() {
  BUFFER=$(fc -l -n 1 | tail -r | awk '!a[$0]++' | peco --query "$LBUFFER")
  CURSOR=$#BUFFER
  zle redisplay
}
zle -N peco-select-history
bindkey '^h' peco-select-history

_peco_mdfind() {
  result=$(mdfind -onlyin ~/Dropbox -onlyin ~/Repos/src "kMDItemKind==\"Folder\"&&kMDItemFSName==\"*$@*\"cd" | grep -v "node_modules" | peco)
  if [ -n "$result" ]; then
    cd $result; clear
  fi
}
alias search="_peco_mdfind"


update() {
  pushd $DOTFILES_DIR && git pull && popd
  reload
  brew upgrade
  gem update
  apm update --no-confirm
  npm-check -gu
  pip-update
  mas upgrade
}


gu() {
  gtPrivateKeyPath=$(git config remote.origin.gtPrivateKeyPath)
  privateKeyPath=${gtPrivateKeyPath:-~/.ssh/id_rsa}
  gitUser=$(git config user.name)
  gitEmail=$(git config user.email)
  echo "Name: ${gitUser}"
  echo "Mail: ${gitEmail}"
  echo "Private: ${privateKeyPath}"
  echo ""
  GIT_SSH_COMMAND="ssh -i ${privateKeyPath} -oIdentitiesOnly=yes" $@
}


# zprof
